language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

sudo: false

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: ./vendor/phpunit/phpunit/phpunit --bootstrap phpunit.bootstrap.php ./tests

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm
  fast_finish: true
